### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by OliverCullimore** [Jman012/Wasserflug-tvOS#27]
On the Roku & AndroidTV projects, they're adopting issue templates to prompt the required information for debugging issues / implemented features to be gathered and also direct users to leave issues on the right GitHub project for the platform they're using.

Hydravion-AndroidTV's implementation of this can be found [here](https://github.com/bmlzootown/Hydravion-AndroidTV/pull/34)

If you'd like to do the same for Wasserflug here's a start below:

.github/ISSUE_TEMPLATE/1-bug.yml
```
name: 🐛 Apple TV/tvOS (Wasserflug) bug report
description: Report a bug/issue affecting Apple TV/tvOS (Wasserflug)
labels: ["bug"]
body:
    - type: checkboxes
      attributes:
        label: Checklist before submitting a bug report
        options:
        - label: This bug/issue is affecting Apple TV/tvOS (Wasserflug)
          required: true
        - label: I've searched for existing [issues](https://github.com/Jman012/Wasserflug-tvOS/issues?q=is:issue) and found no duplicates
          required: true
        - label: I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed
          required: true

    - type: input
      id: devicemodel
      attributes:
          label: Model
          description: REMOVE / UPDATE WITH INSTRUCTIONS
          placeholder: e.g. Apple TV 4K (2nd generation)
      validations:
          required: true

    - type: input
      id: osversion
      attributes:
          label: tvOS Version
          description: REMOVE / UPDATE WITH INSTRUCTIONS
          placeholder: e.g. tvOS 17.1
      validations:
          required: true

    - type: input
      id: version
      attributes:
          label: Wasserflug Version
          description: REMOVE / UPDATE WITH INSTRUCTIONS
          placeholder: e.g. 1.3.0
      validations:
          required: true

    - type: input
      id: subscriptions
      attributes:
          label: Whom you are subscribed to?
          description: Sometimes issues are subscription specific
          placeholder: e.g. LTT, Garbage Time, Bitwit, Lvl1
      validations:
          required: true

    - type: markdown
      attributes:
        value: Please detail one bug per GitHub issue

    - type: textarea
      id: details
      attributes:
        label: Error/Issue Details
        description: |
          What is the issue you're experiencing? How can we re-produce it?
          Please be as specific as possible
          - Is the error/issue occurring on a specific channel only?
          - Does it only affect specific videos?
          - Does the issue still occur when trying to play the video at a different resolution? (Access the options menu when looking at the video description, "Select Resolution")
          - Can you provide any screenshots?
        placeholder: Detailed explanation of the issue along with replication steps
```

.github/ISSUE_TEMPLATE/1-bug.yml
```
name: 🚀 Apple TV/tvOS (Wasserflug) feature request
description: Feature request for Apple TV/tvOS (Wasserflug)
labels: ["enhancement"]
body:
    - type: checkboxes
      attributes:
        label: Checklist before submitting a feature request
        options:
        - label: This feature request is for Apple TV/tvOS (Wasserflug)
          required: true
        - label: I've searched for existing [requests](https://github.com/Jman012/Wasserflug-tvOS/issues?q=is:issue) and found no duplicates
          required: true
        - label: I understand that this project is run by volunteer contributors therefore completion of this request cannot be guaranteed
          required: true

    - type: markdown
      attributes:
        value: Please detail one feature request per GitHub issue

    - type: textarea
      id: details
      attributes:
        label: New Feature Details
        description: |
          What would be the expected behavior of the new feature?
          Are there any links/screenshots that can be provided relating to this?
        placeholder: Detailed explanation of the new feature
      validations:
        required: true
```

config.yml
```
blank_issues_enabled: true
contact_links:
  - name: AndroidTV issues, feedback & feature requests
    url: https://github.com/bmlzootown/Hydravion-AndroidTV/issues
    about: Please use the Hydravion-AndroidTV issues page

  - name: Roku issues, feedback & feature requests
    url: https://github.com/bmlzootown/Hydravion/issues
    about: Please use the Hydravion Roku issues page

  - name: Questions
    url: https://discord.gg/4xKDGz5M5B
    about: Join the Discord server for help with regular/general questions
```
